{% set name = "behave-django" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e253a4abc748559a0f9ad019349244fb0e4287f9cc70790dd0d20f3daf23c19e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - django >=4.2
    - python >={{ python_min }}
    - beautifulsoup4
    - behave ==1.2.7.dev6
    # - django >=4.2

test:
  imports:
    - behave_django
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/behave/behave-django
  summary: Behave BDD integration for Django
  doc_url: https://pythonhosted.org/behave-django/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
